import { RalphCodexConfig } from './types';

export const DEFAULT_CONFIG: RalphCodexConfig = {
  codexCommandPath: 'codex',
  preferredHandoffMode: 'ideCommand',
  inspectionRootOverride: '',
  ralphIterationCap: 20,
  verifierModes: ['validationCommand', 'gitDiff', 'taskState'],
  noProgressThreshold: 5,
  repeatedFailureThreshold: 5,
  artifactRetentionPath: '.ralph/artifacts',
  generatedArtifactRetentionCount: 25,
  provenanceBundleRetentionCount: 25,
  gitCheckpointMode: 'snapshotAndDiff',
  validationCommandOverride: '',
  stopOnHumanReviewNeeded: true,
  autoReplenishBacklog: false,
  ralphTaskFilePath: '.ralph/tasks.json',
  prdPath: '.ralph/prd.md',
  progressPath: '.ralph/progress.md',
  promptTemplateDirectory: '',
  promptIncludeVerifierFeedback: true,
  promptPriorContextBudget: 8,
  clipboardAutoCopy: true,
  model: 'gpt-5.4',
  reasoningEffort: 'medium',
  approvalMode: 'never',
  sandboxMode: 'workspace-write',
  openSidebarCommandId: 'chatgpt.openSidebar',
  newChatCommandId: 'chatgpt.newChat'
};
