import { RalphCodexConfig, RalphHooksConfig, RalphModelTieringConfig } from './types';

export const DEFAULT_CONFIG: RalphCodexConfig = {
  cliProvider: 'claude',
  codexCommandPath: 'codex',
  claudeCommandPath: 'claude',
  copilotCommandPath: 'copilot',
  claudeMaxTurns: 50,
  claudePermissionMode: 'dangerously-skip-permissions',
  copilotApprovalMode: 'allow-all',
  agentId: 'default',
  agentRole: 'build',
  preferredHandoffMode: 'ideCommand',
  inspectionRootOverride: '',
  ralphIterationCap: 20,
  verifierModes: ['validationCommand', 'gitDiff', 'taskState'],
  noProgressThreshold: 5,
  repeatedFailureThreshold: 5,
  artifactRetentionPath: '.ralph/artifacts',
  generatedArtifactRetentionCount: 25,
  provenanceBundleRetentionCount: 25,
  gitCheckpointMode: 'snapshotAndDiff',
  scmStrategy: 'none',
  scmPrOnParentDone: false,
  watchdogStaleTtlMs: 24 * 60 * 60 * 1000,
  validationCommandOverride: '',
  stopOnHumanReviewNeeded: true,
  autonomyMode: 'supervised',
  autoReplenishBacklog: false,
  autoReloadOnControlPlaneChange: false,
  autoApplyRemediation: [],
  ralphTaskFilePath: '.ralph/tasks.json',
  prdPath: '.ralph/prd.md',
  progressPath: '.ralph/progress.md',
  promptTemplateDirectory: '',
  promptIncludeVerifierFeedback: true,
  promptPriorContextBudget: 8,
  promptBudgetProfile: 'codex',
  customPromptBudget: {},
  clipboardAutoCopy: true,
  model: 'claude-sonnet-4-6',
  reasoningEffort: 'medium',
  approvalMode: 'never',
  sandboxMode: 'workspace-write',
  openSidebarCommandId: 'claude.openSidebar',
  newChatCommandId: 'claude.newChat',
  claimTtlHours: 24,
  staleLockThresholdMinutes: 5,
  agentCount: 1,
  modelTiering: {
    enabled: false,
    simpleModel: 'claude-haiku-4-5-20251001',
    mediumModel: 'claude-sonnet-4-6',
    complexModel: 'claude-opus-4-6',
    simpleThreshold: 2,
    complexThreshold: 6
  } satisfies RalphModelTieringConfig,
  hooks: {} satisfies RalphHooksConfig,
  autoWatchdogOnStall: false,
  autoReviewOnParentDone: false,
  autoReviewOnLoopComplete: false,
  autoScmOnConflict: false,
  scmConflictRetryLimit: 1,
  pipelineHumanGates: false
};
